# Generated by Django 3.0.1 on 2020-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicos', '0002_electronico_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronico',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronico',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
