# Generated by Django 3.0.1 on 2020-01-07 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipocolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipomarca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoprenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.tipocolor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.tipomarca')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prendas.tipoprenda')),
            ],
        ),
    ]
