# Generated by Django 3.0.1 on 2020-01-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0003_auto_20200112_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='uso',
            field=models.BooleanField(default=False),
        ),
    ]
