# Generated by Django 3.0.1 on 2020-02-23 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0005_tipocolor_ejemplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prenda',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000, 'Debe ser menor de 100,000'), django.core.validators.MinValueValidator(1, 'Debe haber al menos 1')]),
        ),
    ]
