# Generated by Django 3.0.1 on 2020-04-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_auto_20200323_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='tipo',
            field=models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Deportivos', 'Deportivos'), ('Compactos', 'Compactos'), ('Cupés', 'Cupés'), ('Emergencias', 'Emergencias'), ('Industriales', 'Industriales'), ('Militares', 'Militares'), ('Todoterrenos', 'Todoterrenos'), ('Muscle', 'Muscle'), ('Sedanes', 'Sedanes'), ('Servicio', 'Servicio'), ('Deportivo clasicos', 'Deportivo clásicos'), ('Súper', 'Súper'), ('Todocaminos', 'Todocaminos'), ('Especializados', 'Especializados'), ('Furgonetas', 'Furgonetas'), ('Ruedas descubiertas', 'Ruedas descubiertas')], max_length=100),
        ),
    ]
