# Generated by Django 3.0.1 on 2020-01-27 04:31

from django.db import migrations
import spectrum.fields


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0004_prenda_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocolor',
            name='ejemplo',
            field=spectrum.fields.ColorField(default='#FFFF00', verbose_name='color'),
        ),
    ]
