# Generated by Django 3.0.1 on 2020-02-23 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronicos', '0003_auto_20200219_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronico',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000, 'Debe ser menos de 100,000'), django.core.validators.MinValueValidator(1, 'Debe haber al menos 1')]),
        ),
        migrations.AlterField(
            model_name='electronico',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MaxValueValidator(1000000, 'Debe ser menor a 1,000,000'), django.core.validators.MinValueValidator(0, 'Debe ser 0 o mayor')]),
        ),
        migrations.AlterField(
            model_name='electronico',
            name='disponible',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000, 'Debe ser menos de 100,000'), django.core.validators.MinValueValidator(0, 'Debe ser 0 o mayor')]),
        ),
    ]
