# Generated by Django 3.0.1 on 2020-02-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_20200222_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(choices=[('Nagasaki', 'Nagasaki'), ('Shitzu', 'Shitzu'), ('Dinka', 'Dinka'), ('Vapid', 'Vapid'), ('Albany', 'Albany'), ('Invetero', 'Invetero'), ('Imponte', 'Imponte'), ('Bravado', 'Bravado'), ('Cheval', 'Cheval'), ('Declasse', 'Declasse'), ('Enus', 'Enus'), ('Dewbauchee', 'Dewbauchee'), ('Lampadati', 'Lampadati'), ('Ocelot', 'Ocelot'), ('Ubermacht', 'Ubermacht'), ('HVY', 'HVY'), ('Jobuilt', 'Jobuilt'), ('Maibatsu', 'Maibatsu'), ('MTL', 'MTL'), ('Brute', 'Brute'), ('Dinka', 'Dinka'), ('Karin', 'Karin'), ('Weeny', 'Weeny'), ('Benefactor', 'Benefactor'), ('Bollokan', 'Bollokan'), ('Obey', 'Obey'), ('Grotti', 'Grotti'), ('Pifster', 'Pifster'), ('Annis', 'Annis'), ('Schyster', 'Schyster'), ('Hijak', 'Hijak'), ('Pegassi', 'Pegassi'), ('Truffade', 'Truffade'), ('Western', 'Western'), ('Stanley', 'Stanley'), ('Zirconium', 'Zirconium'), ('LCC', 'LCC'), ('Principe', 'Principe'), ('Gallivanter', 'Gallivanter'), ('Fathom', 'Fathom'), ('Emperor', 'Emperor'), ('Dundreary', 'Dundreary'), ('Mammoth', 'Mammoth'), ('Canis', 'Canis'), ('BF', 'BF'), ('Coil', 'Coil'), ('Vulcar', 'Vulcar'), ('Överflöd', 'Överflöd'), ('Progen', 'Progen'), ('Willard', 'Willard'), ('Maxwell', 'Maxwell'), ('Vysser', 'Vysser'), ('Vom Feuer', 'Vom Feuer'), ('Desconocido', 'Desconocido')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(choices=[('Motocicleta', 'Motocicleta'), ('Deportivos', 'Deportivos'), ('Compactos', 'Compactos'), ('Cupés', 'Cupés'), ('Emergencias', 'Emergencias'), ('Industriales', 'Industriales'), ('Militares', 'Militares'), ('Todoterrenos', 'Todoterrenos'), ('Muscle', 'Muscle'), ('Sedanes', 'Sedanes'), ('Servicio', 'Servicio'), ('Deportivo clasicos', 'Deportivo clásicos'), ('Súper', 'Súper'), ('Todocaminos', 'Todocaminos'), ('Especializados', 'Especializados'), ('Furgonetas', 'Furgonetas'), ('De competición', 'De competición')], max_length=100),
        ),
    ]
